from fastapi import APIRouter

from app.api.routes import (
    adaptive,
    adaptive_metrics,
    agent,
    courses,
    course_architecture,
    daily_tasks,
    dashboard,
    diagnostics,
    demo,
    health,
    learning_goals,
    knowledge_point_sources,
    learning_sessions,
    learning_activities,
    materials,
    material_learning,
    quiz_attempts,
    rag,
    wrong_answers,
    mastery,
    notes,
    reviews,
    study_plans,
    next_learning_action,
    learning_runtime,
    lessons,
    curriculum,
    plan_adjustments,
)

api_router = APIRouter()
for router in (
    mastery.router,
    reviews.router,
    adaptive.router,
    adaptive_metrics.router,
    agent.router,
    learning_runtime.router,
    lessons.router,
    curriculum.router,
    plan_adjustments.router,
    health.router,
    notes.router,
    learning_goals.router,
    knowledge_point_sources.router,
    materials.router,
    material_learning.router,
    course_architecture.router,
    diagnostics.router,
    study_plans.router,
    next_learning_action.router,
    courses.router,
    daily_tasks.router,
    learning_sessions.router,
    learning_activities.router,
    dashboard.router,
    demo.router,
    rag.router,
    quiz_attempts.router,
    wrong_answers.router,
):
    api_router.include_router(router)
